name: Update
on:
  workflow_dispatch:
  schedule:
    # At 10:00 UTC on Friday.
    - cron: '0 10 * * 5'

jobs:
  svg:
    name: SVG
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.09

      - name: Install wkhtmltopdf
        run: |
          nix-env -i wkhtmltopdf -f '<nixpkgs>'
          wkhtmltoimage --version

      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Render HTML to SVG
        run: wkhtmltoimage --disable-javascript --width 720 --user-style-sheet self.css 'https://b1nary.tk/~tie' self.svg

      - name: Create PR
        uses: peter-evans/create-pull-request@v3.9.2
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'Rebuild SVG from HTML'
          branch: update-svg
          delete-branch: true
          title: Update SVG
          body: |
            This PR updates SVG image using the latest HTML profile page.
